# Development Docker Compose configuration
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=development-secret-key-minimum-32-characters-long-for-testing-purposes
      - DATABASE_URL=sqlite:///./dev.db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - WHATSAPP_TOKEN=test_token_placeholder
      - WHATSAPP_PHONE_ID=test_phone_id_placeholder
      - WHATSAPP_VERIFY_TOKEN=test_verify_token_placeholder
      - WHATSAPP_APP_SECRET=test_app_secret_placeholder
      - INSPECTOR_API_BASE_URL=https://api.inspector.com
      - INSPECTOR_API_KEY=test_inspector_api_key_placeholder
      - SMTP_USER=test@example.com
      - SMTP_PASSWORD=test_password
    volumes:
      - ./logs:/app/logs
      - ./dev.db:/app/dev.db
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data: